/* Generated By:JavaCC: Do not edit this line. MiParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPRIMIR = 5;
  /** RegularExpression Id. */
  int IMPORTAR = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int RANGE = 12;
  /** RegularExpression Id. */
  int PIZQUIERDO = 13;
  /** RegularExpression Id. */
  int PDERECHO = 14;
  /** RegularExpression Id. */
  int LLAVEIZQ = 15;
  /** RegularExpression Id. */
  int LLAVEDER = 16;
  /** RegularExpression Id. */
  int COMA = 17;
  /** RegularExpression Id. */
  int MENORQUE = 18;
  /** RegularExpression Id. */
  int MAYORQUE = 19;
  /** RegularExpression Id. */
  int MENORIGUAL = 20;
  /** RegularExpression Id. */
  int MAYORIGUAL = 21;
  /** RegularExpression Id. */
  int IGUALQUE = 22;
  /** RegularExpression Id. */
  int ASIGNACION = 23;
  /** RegularExpression Id. */
  int SUMA = 24;
  /** RegularExpression Id. */
  int RESTA = 25;
  /** RegularExpression Id. */
  int MULTIPLICACION = 26;
  /** RegularExpression Id. */
  int DIVISION = 27;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 28;
  /** RegularExpression Id. */
  int NUMERO = 29;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 30;
  /** RegularExpression Id. */
  int CADENA = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"print\"",
    "\"import\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"in\"",
    "\"range\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENTIFICADOR>",
    "<NUMERO>",
    "\";\"",
    "<CADENA>",
  };

}
